name: Build Docker Images & Push Dockerhub

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Prepare Build Arg
        id: prepare_build_arg
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=CURRENT_TAG::${CURRENT_TAG}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: "nakazii/selenium-side-runner-chrome:${{ steps.prepare_build_arg.outputs.CURRENT_TAG }}"

      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
